# Generated by Django 5.0.2 on 2024-05-31 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0025_alter_expense_record_time_field_alter_group_gname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_record',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 5, 31), null=True),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 5, 31, 19, 17, 43, 414480), null=True),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 5, 31), null=True),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 5, 31, 19, 17, 43, 415476), null=True),
        ),
    ]
