# Generated by Django 5.0.2 on 2024-06-01 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0032_alter_expense_record_time_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_record',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 6, 1), null=True),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 6, 1, 9, 2, 43, 712037), null=True),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 6, 1), null=True),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 6, 1, 9, 2, 43, 713037), null=True),
        ),
    ]
