# Generated by Django 3.2.6 on 2024-06-08 14:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0035_auto_20240607_0810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense_record',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 6, 8), null=True),
        ),
        migrations.AlterField(
            model_name='expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 6, 8, 19, 32, 10, 492495), null=True),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='date_field',
            field=models.DateField(default=datetime.date(2024, 6, 8), null=True),
        ),
        migrations.AlterField(
            model_name='group_expense_record',
            name='time_field',
            field=models.TimeField(default=datetime.datetime(2024, 6, 8, 19, 32, 10, 493504), null=True),
        ),
    ]
